extends:
  [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:import/recommended",
    "plugin:security/recommended",
    "prettier",
  ]
parser: "@typescript-eslint/parser"
plugins: ["@typescript-eslint", "import", "security"]
parserOptions: { ecmaVersion: "latest", sourceType: "module", project: false }
rules:
  {
    quotes: [2, "double"],
    "no-console": 2,
    "import/no-unresolved": 0,
    "@typescript-eslint/no-explicit-any": 2,
    "@typescript-eslint/no-non-null-assertion": 2,
  }
ignorePatterns: ["dist", "node_modules"]
